### ISSUE TITLE
Dyes in dye slots when you die aren't properly saved

### ISSUE THREAD

**Issue by Thirty-Percent** [fcjreed/MediumCoreInventorySaveClock#2]
Thank you for this mod, does what it says except for one detail:
When you have more than 1 of any speific dye in your equipped dyes, die, and then get your stuff back, the 'duplicate' dyes are stacked in your equipped dyes slots. If you then leave the world and rejoin, said stack of dyes in your equipped dye slot is reduced to 1.

For example, I have 3 red dyes in my armor dye slots, one for each piece of armor.
I die and get my inventory back. Everything is put back in place, except my chest and legs dyes which are empty; instead, I have 3 red dyes in my head dye slot. I can then manually re-equip them in each armor dye slot, but if I don't and then leave and rejoin the world (or game), I'm left with only 1 red dye in the head armor dye slot, effectively losing 2 dyes.

Reproduced everytime. Installed mods: tmodloader, recipe browser, unleveled.

Thanks again!

**Comment by fcjreed** [comment]
Hmm. I was going through the logic and trying to understand how this would happen. I think what happens is the dyes end up stacking when they fall out of the inventory. Let me see what I can do to figure out handling that.

**Comment by fcjreed** [comment]
Tests looked good on the changes. @robert11arad can you review/merge/publish once you get a chance?

**Comment by fcjreed** [comment]
I don't have access to publish a new version. We'll have to wait for @robert11arad , but I feel like this won't work when the new version comes out.

**Comment by Thirty-Percent** [comment]
> 
> 
> I don't have access to publish a new version. We'll have to wait for @robert11arad , but I feel like this won't work when the new version comes out.

I see, thanks for answering. I can live with that. Either way, all I need is less dy(e)ing :)
Small suggestion while I'm here (likely for after tomorrow's big update), not sure if it's doable: printing a message in chat when a player recovers their inventory, to remind them to press Home if they wish to save again?
Alternatively, a bit more complicated I guess, adding separate, successive inventory saves, with the first (oldest) one taking priority over the others. For example, player dies at 12:00, goes to pickup their inventory but dies on the way at 13:00, then again at 14:00.
Three separate saves are made, and when the player gets their 14:00 inventory, items are put back in place and the 14:00 save is deleted. Then when they get their 13:00 inventory, it overrides the 14:00 save, moving 14:00's items to make room for the 13's. Same for the 12:00 save, and if there's no more room in the inventory at this point, auto throw the most recent death's recovered items to make room for the items recovered last (but dropped first... I hope that makes sense)
Then let's say they get their 13:00 inventory before the 14:00 one; the 14:00 inventory having lower priority wouldn't override 13:00 item positions.
I guess that would require a separate file to keep track of different saves' priority levels based on their "time since dropped"
Anyway, cheers

**Comment by fcjreed** [comment]
Sorry, the issue auto closed. That would be a feature request. However, I'm pretty busy with work lately and most likely will wait for 1.4 mod support to start working on it again.
